### ISSUE TITLE
Erro na localização de arquivo

### ISSUE THREAD

**Issue by gabriel-masson** [FelipeRodriguees/NLW-NextLevelWeek-Discovery#1]
oi felipe,eu estva vendo o arquivo
 do dia-do-evento/_thridday/give-
classes.html, e observei que na
linha 120 você colocou _images...
 _images/icons/warning.svg 
isso poderar causar algum erro em outra maquina(na minha por exemplo)
tente usar o /images...
a / no inicio significa que ira buscar o arquivo desde a raiz,isso pode evitar erros mais a frente no projeto.
 /images/icons/warning.svg

**Comment by FelipeRodriguees** [comment]
Olá Gabriel.
Bem observado, obrigado pelo toque.
Irei arrumar isso, obg.
